from dataclasses import dataclass


@dataclass(frozen=True)
class CatalogInstrument:
    ticker: str
    name: str
    asset_type: str       # "etf" | "stock" | "crypto" | "bond"
    market: str           # "US" | "EU" | "GLOBAL" | "CRYPTO"
    currency: str
    risk_level: str       # "low" | "moderate" | "high" | "very_high"
    typical_horizon: str  # "short_term" | "medium_term" | "long_term"
    asset_family: str     # "preservation" | "balanced" | "growth" | "speculative"
    categories: tuple[str, ...]  # subset of preferred_assets option values
    suitable_for_beginners: bool
    brief_rationale: str


CATALOG: list[CatalogInstrument] = [
    # ── Preservation — Low Risk ───────────────────────────────────────────────
    CatalogInstrument(
        ticker="AGG",
        name="iShares Core US Aggregate Bond ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="low",
        typical_horizon="long_term",
        asset_family="preservation",
        categories=("etf", "bonds"),
        suitable_for_beginners=True,
        brief_rationale="Broad exposure to US investment-grade bonds; stable income, low volatility.",
    ),
    CatalogInstrument(
        ticker="BND",
        name="Vanguard Total Bond Market ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="low",
        typical_horizon="long_term",
        asset_family="preservation",
        categories=("etf", "bonds"),
        suitable_for_beginners=True,
        brief_rationale="Low-cost diversified US bond exposure across government and corporate debt.",
    ),
    CatalogInstrument(
        ticker="SHY",
        name="iShares 1-3 Year Treasury Bond ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="low",
        typical_horizon="short_term",
        asset_family="preservation",
        categories=("etf", "bonds"),
        suitable_for_beginners=True,
        brief_rationale="Short-duration US Treasuries; capital preservation with minimal interest rate risk.",
    ),
    CatalogInstrument(
        ticker="GLD",
        name="SPDR Gold Shares",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="low",
        typical_horizon="medium_term",
        asset_family="preservation",
        categories=("etf", "commodities"),
        suitable_for_beginners=True,
        brief_rationale="Physical gold exposure; classic inflation hedge and portfolio stabilizer.",
    ),
    # ── Balanced — Moderate Risk ──────────────────────────────────────────────
    CatalogInstrument(
        ticker="SPY",
        name="SPDR S&P 500 ETF Trust",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="Tracks the S&P 500; the most widely held index ETF globally. Core long-term holding.",
    ),
    CatalogInstrument(
        ticker="VOO",
        name="Vanguard S&P 500 ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="Ultra-low-cost S&P 500 exposure. Suitable as a primary portfolio building block.",
    ),
    CatalogInstrument(
        ticker="VTI",
        name="Vanguard Total Stock Market ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="Covers the entire US equity market including small and mid caps beyond the S&P 500.",
    ),
    CatalogInstrument(
        ticker="VT",
        name="Vanguard Total World Stock ETF",
        asset_type="etf",
        market="GLOBAL",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="Single-fund global equity exposure — US and international markets in one ETF.",
    ),
    CatalogInstrument(
        ticker="VXUS",
        name="Vanguard Total International Stock ETF",
        asset_type="etf",
        market="GLOBAL",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="Broad international diversification across developed and emerging markets ex-US.",
    ),
    CatalogInstrument(
        ticker="IWDA",
        name="iShares Core MSCI World ETF",
        asset_type="etf",
        market="EU",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="UCITS-compliant global developed market ETF; popular for EU-based investors.",
    ),
    CatalogInstrument(
        ticker="CSPX",
        name="iShares Core S&P 500 UCITS ETF",
        asset_type="etf",
        market="EU",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="EU-listed S&P 500 tracker; UCITS-compliant and tax-efficient for many EU investors.",
    ),
    CatalogInstrument(
        ticker="SCHD",
        name="Schwab US Dividend Equity ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "stocks"),
        suitable_for_beginners=True,
        brief_rationale="High-quality dividend-paying US equities; income-focused with lower volatility than pure growth.",
    ),
    CatalogInstrument(
        ticker="VNQ",
        name="Vanguard Real Estate ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("etf", "real_estate"),
        suitable_for_beginners=True,
        brief_rationale="Diversified US REIT exposure; real estate income without direct property ownership.",
    ),
    CatalogInstrument(
        ticker="DJP",
        name="iPath Bloomberg Commodity Index ETN",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="medium_term",
        asset_family="balanced",
        categories=("etf", "commodities"),
        suitable_for_beginners=False,
        brief_rationale="Broad commodity exposure across energy, agriculture, and metals; inflation hedge.",
    ),
    # ── Growth — High Risk ────────────────────────────────────────────────────
    CatalogInstrument(
        ticker="QQQ",
        name="Invesco QQQ Trust (Nasdaq-100)",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("etf", "stocks"),
        suitable_for_beginners=False,
        brief_rationale="Top 100 Nasdaq companies — heavy technology tilt with strong long-term growth track record.",
    ),
    CatalogInstrument(
        ticker="VGT",
        name="Vanguard Information Technology ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("etf", "stocks"),
        suitable_for_beginners=False,
        brief_rationale="Concentrated US technology sector ETF. High growth potential with elevated volatility.",
    ),
    CatalogInstrument(
        ticker="SOXX",
        name="iShares Semiconductor ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("etf", "stocks"),
        suitable_for_beginners=False,
        brief_rationale="Pure-play semiconductor sector exposure. High upside in AI/chip cycles, high cyclical risk.",
    ),
    CatalogInstrument(
        ticker="EEM",
        name="iShares MSCI Emerging Markets ETF",
        asset_type="etf",
        market="GLOBAL",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("etf", "stocks"),
        suitable_for_beginners=False,
        brief_rationale="Exposure to fast-growing emerging economies (China, India, Brazil). Higher volatility.",
    ),
    CatalogInstrument(
        ticker="AAPL",
        name="Apple Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="World's largest company by market cap. Strong brand, services growth, consistent buybacks.",
    ),
    CatalogInstrument(
        ticker="MSFT",
        name="Microsoft Corporation",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Cloud (Azure) and AI leadership alongside enterprise software dominance.",
    ),
    # ── Speculative — Very High Risk ──────────────────────────────────────────
    CatalogInstrument(
        ticker="NVDA",
        name="NVIDIA Corporation",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="medium_term",
        asset_family="speculative",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Dominant AI infrastructure chip maker. Exceptional growth; extreme valuation and volatility.",
    ),
    CatalogInstrument(
        ticker="ARKK",
        name="ARK Innovation ETF",
        asset_type="etf",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("etf", "stocks"),
        suitable_for_beginners=False,
        brief_rationale="Actively managed disruptive innovation ETF. High upside in bull markets; high drawdown risk.",
    ),
    CatalogInstrument(
        ticker="COIN",
        name="Coinbase Global Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="medium_term",
        asset_family="speculative",
        categories=("stocks", "crypto"),
        suitable_for_beginners=False,
        brief_rationale="Largest US crypto exchange. Proxy for crypto market sentiment; high regulatory and price risk.",
    ),
    CatalogInstrument(
        ticker="BTC-USD",
        name="Bitcoin",
        asset_type="crypto",
        market="CRYPTO",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("crypto",),
        suitable_for_beginners=False,
        brief_rationale="Largest cryptocurrency by market cap. Store-of-value thesis; very high volatility.",
    ),
    CatalogInstrument(
        ticker="ETH-USD",
        name="Ethereum",
        asset_type="crypto",
        market="CRYPTO",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("crypto",),
        suitable_for_beginners=False,
        brief_rationale="Leading smart contract platform powering DeFi and Web3. High growth and volatility.",
    ),
    # ── More Crypto ───────────────────────────────────────────────────────────────
    CatalogInstrument(
        ticker="SOL-USD",
        name="Solana",
        asset_type="crypto",
        market="CRYPTO",
        currency="USD",
        risk_level="very_high",
        typical_horizon="medium_term",
        asset_family="speculative",
        categories=("crypto",),
        suitable_for_beginners=False,
        brief_rationale="High-speed blockchain with strong DeFi and NFT ecosystem. High growth potential with significant volatility.",
    ),
    CatalogInstrument(
        ticker="BNB-USD",
        name="BNB (Binance Coin)",
        asset_type="crypto",
        market="CRYPTO",
        currency="USD",
        risk_level="very_high",
        typical_horizon="medium_term",
        asset_family="speculative",
        categories=("crypto",),
        suitable_for_beginners=False,
        brief_rationale="Native token of Binance ecosystem. Utility-driven demand with exchange fee discounts and DeFi use cases.",
    ),
    CatalogInstrument(
        ticker="ADA-USD",
        name="Cardano",
        asset_type="crypto",
        market="CRYPTO",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("crypto",),
        suitable_for_beginners=False,
        brief_rationale="Research-driven smart contract platform with a strong academic foundation. Lower valuation than ETH/SOL.",
    ),
    # ── NASDAQ — Additional US Growth ────────────────────────────────────────────
    CatalogInstrument(
        ticker="AMZN",
        name="Amazon.com Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Cloud (AWS) and e-commerce dominance. Expanding advertising and AI capabilities.",
    ),
    CatalogInstrument(
        ticker="GOOGL",
        name="Alphabet Inc. (Google)",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Search, cloud, and AI leadership. YouTube and Waymo provide long-term optionality.",
    ),
    CatalogInstrument(
        ticker="META",
        name="Meta Platforms Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Dominant social media advertising. Heavy AI investment with Reality Labs as long-term optionality.",
    ),
    CatalogInstrument(
        ticker="TSLA",
        name="Tesla Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="EV leader expanding into energy storage and autonomous driving. Very high volatility; sentiment-driven.",
    ),
    # ── High-Growth US Stocks ──────────────────────────────────────────────────
    CatalogInstrument(
        ticker="AMD",
        name="Advanced Micro Devices",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Direct NVIDIA competitor in AI GPUs and data centre CPUs. High growth potential; trades at a significant discount to NVDA.",
    ),
    CatalogInstrument(
        ticker="PLTR",
        name="Palantir Technologies",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="very_high",
        typical_horizon="long_term",
        asset_family="speculative",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="AI-driven data analytics for government and enterprise. Strong US government contracts; fast-growing commercial segment.",
    ),
    CatalogInstrument(
        ticker="NFLX",
        name="Netflix Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Dominant global streaming platform. Ad-supported tier and live sports driving new revenue streams.",
    ),
    CatalogInstrument(
        ticker="CRM",
        name="Salesforce Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Leading cloud CRM platform expanding into AI agents (Agentforce). Large installed base with high switching costs.",
    ),
    # ── Financial & Value US Stocks ────────────────────────────────────────────
    CatalogInstrument(
        ticker="JPM",
        name="JPMorgan Chase & Co.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="World's largest bank by market cap. Diversified revenue, strong balance sheet, consistent dividend payer.",
    ),
    CatalogInstrument(
        ticker="V",
        name="Visa Inc.",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Global payments network with near-monopoly economics. Consistent double-digit earnings growth and buybacks.",
    ),
    CatalogInstrument(
        ticker="XOM",
        name="ExxonMobil Corporation",
        asset_type="stock",
        market="US",
        currency="USD",
        risk_level="moderate",
        typical_horizon="medium_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="World's largest publicly traded energy company. Strong free cash flow, growing dividend, energy security tailwind.",
    ),
    # ── TASE (Tel Aviv Stock Exchange) ───────────────────────────────────────────
    CatalogInstrument(
        ticker="BEZQ.TA",
        name="Bezeq Israeli Telecom",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="low",
        typical_horizon="long_term",
        asset_family="preservation",
        categories=("stocks",),
        suitable_for_beginners=True,
        brief_rationale="Israel's dominant fixed-line and broadband operator. Defensive dividend income in ILS.",
    ),
    CatalogInstrument(
        ticker="POLI.TA",
        name="Bank Hapoalim",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Israel's largest bank. Consistent dividend payer with strong local market position.",
    ),
    CatalogInstrument(
        ticker="LUMI.TA",
        name="Bank Leumi",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Israel's second-largest bank. Solid fundamentals and ILS-denominated returns.",
    ),
    CatalogInstrument(
        ticker="ICL.TA",
        name="ICL Group",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="moderate",
        typical_horizon="long_term",
        asset_family="balanced",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Global specialty minerals and chemicals leader. Commodity-linked with geographic diversification.",
    ),
    CatalogInstrument(
        ticker="TEVA.TA",
        name="Teva Pharmaceutical Industries",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="World's largest generic drug maker. Restructuring phase; high upside potential with elevated risk.",
    ),
    CatalogInstrument(
        ticker="NICE.TA",
        name="NICE Ltd",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Israeli AI and enterprise software leader. Cloud transition driving strong recurring revenue growth.",
    ),
    CatalogInstrument(
        ticker="ESLT.TA",
        name="Elbit Systems",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="high",
        typical_horizon="long_term",
        asset_family="growth",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Israel's leading defense electronics company. Strong export revenue with rising global defense budgets.",
    ),
    CatalogInstrument(
        ticker="DLEKG.TA",
        name="Delek Group",
        asset_type="stock",
        market="TASE",
        currency="ILS",
        risk_level="very_high",
        typical_horizon="medium_term",
        asset_family="speculative",
        categories=("stocks",),
        suitable_for_beginners=False,
        brief_rationale="Israeli energy holding company with natural gas and E&P assets. High leverage; highly sensitive to energy prices.",
    ),
]
