apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradeops.fullname" . }}-backend
  labels:
    {{- include "tradeops.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tradeops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
