{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradeops.fullname" . }}-redis
  labels:
    {{- include "tradeops.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "tradeops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
{{- end }}
